# Project basic info
sonar.projectKey=my-drawing-app
sonar.projectName=MyDrawingApp
sonar.host.url=http://localhost:9000

# Source files (all files in this folder)
sonar.sources=.

# Exclude node_modules or build folders
sonar.exclusions=node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8
